#############################################################
#
# KFILESYSTEM----提供给USBMOUNT挂载的文件系统选项
#
#############################################################

#
# Dependencies
#
KFILESYSTEM_DEPENDENCIES = 

#############################################################
### Version and change logs area
KFILESYSTEM_VERSION = V1.00

define KFILESYSTEM_CHANGELOGS
V1.00:
	1. First release by w00190448

endef
#############################################################

KFILESYSTEM_TYPE=atpkconfig

define KFILESYSTEM_LINUX_CONFIGURE_CMDS

#支持NTFS
ifeq ($(BUILD_NTFS),y)
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_NTFS_FS,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_NTFS_DEBUG,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_NTFS_RW,$$(KERNEL_CONFIG_FILE))
endif

#支持EXT2&3
ifeq ($(BUILD_KERNEL_EXT2_FS),y)
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_EXT2_FS,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_EXT2_FS_XATTR,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_EXT2_FS_POSIX_ACL,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_EXT2_FS_SECURITY,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_EXT2_FS_XIP,$$(KERNEL_CONFIG_FILE))
endif

ifeq ($(BUILD_KERNEL_EXT3_FS),y)
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_EXT3_FS,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_EXT3_DEFAULTS_TO_ORDERED,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_EXT3_FS_XATTR,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_EXT3_FS_POSIX_ACL,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_EXT3_FS_SECURITY,$$(KERNEL_CONFIG_FILE))
endif

#支持HFS&HFS+
ifeq ($(BUILD_KERNEL_HFS_FS),y)
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_HFS_FS,$$(KERNEL_CONFIG_FILE))
endif

ifeq ($(BUILD_KERNEL_HFSPLUS_FS),y)
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_HFSPLUS_FS,$$(KERNEL_CONFIG_FILE))
endif

	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_MAC_PARTITION,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_EFI_PARTITION,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_SCSI_MULTI_LUN,$$(KERNEL_CONFIG_FILE))

endef


$(eval $(call ATPTARGETS,package/atp/applications/filesystem/kernel,kfilesystem,BUILD_FILESYSTEM_SELECTION))
