################### depend objects
OBJS = gena_callback2.o gena_ctrlpt.o gena_device.o

######################### compile options
CFLAGS = -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64

include $(TOPDIR)/package/atp/rule.mak


