#############################################################
#
# KDMS
#
#############################################################

#
# Dependencies
#
KDMS_DEPENDENCIES =

#############################################################
### Version and change logs area
KDMS_VERSION = V1.00

define KDMS_CHANGELOGS
V1.00:
	1. First release by <<ccmm>>.

endef
#############################################################

# Program name
KDMS_PROGRAM_NAME=kdms

# Target name
KDMS_TARGET=static

KDMS_TYPE=atpkconfig

KDMS_INDEX=229


define KDMS_LINUX_CONFIGURE_CMDS

ifeq ($(BUILD_DLNA_OVER_SAMBA),y)
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_NETWORK_FILESYSTEMS,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_SMB_FS,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_SMB_NLS_DEFAULT,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_SET_OPT,CONFIG_SMB_NLS_REMOTE,\"cp437\",$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_CIFS,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_CIFS_STATS,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_CIFS_STATS2,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_CIFS_WEAK_PW_HASH,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_CIFS_XATTR,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_CIFS_POSIX,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_CIFS_DEBUG2,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_CIFS_EXPERIMENTAL,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_INOTIFY,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_INOTIFY_USER,$$(KERNEL_CONFIG_FILE))
else
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_INOTIFY,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_INOTIFY_USER,$$(KERNEL_CONFIG_FILE))
endif

endef

$(eval $(call ATPTARGETS,package/atp/applications/dlna/kernel,kdms,BUILD_DMS))
