#!/bin/bash
set +x

PARAMETERSARRAY=( $* )
MINIPARAMETERNUM=3

if [ ${#PARAMETERSARRAY[@]} -lt ${MINIPARAMETERNUM} ]
then
	echo "The parameters ( ${PARAMETERSARRAY[@]} ) are invalid."
	exit
fi

ATPICPCIDEBUG="prepare-debug-version"
ATPICPCIPARAMETER="ATP_CI=y"
ATPICPCITQEPARAMETER="ATP_CI_TQE=y"
VENDORPARAMETER="VENDOR=${PARAMETERSARRAY[1]}"
COMPILETARGETS=`echo ${PARAMETERSARRAY[@]:${MINIPARAMETERNUM}}`

if [ "${PARAMETERSARRAY[2]}" != "atp" ]
then
CUSTOMERPARAMETER="CUSTOMER=${PARAMETERSARRAY[2]}"
else
CUSTOMERPARAMETER=""
fi


if [ "${PARAMETERSARRAY[0]}" = "debug_yes" ]
then
	echo -ne "\ncompile debug flag...\n"
	make ${VENDORPARAMETER} ${CUSTOMERPARAMETER} ${ATPICPCIDEBUG}
fi

echo "make ${VENDORPARAMETER} ${CUSTOMERPARAMETER} ${ATPICPCIPARAMETER} ${ATPICPCITQEPARAMETER} ${COMPILETARGETS}"
make ${VENDORPARAMETER} ${CUSTOMERPARAMETER} ${ATPICPCIPARAMETER} ${ATPICPCITQEPARAMETER} ${COMPILETARGETS}


exit 0

