#!/bin/bash
set +x

COMPILETARGETS=""

PARAMETERSARRAY=( $* )
VALIDPARAMETERNUM=3
MINICOMPILETARGETSNUM=1

if [ ${#PARAMETERSARRAY[@]} -ne ${VALIDPARAMETERNUM} ]
then
	echo "The parameters ( ${PARAMETERSARRAY[@]} ) are invalid."
	exit -1
fi

ATPICPCIDEBUG="prepare-debug-version"
ATPICPCIPARAMETER="ATP_CI=y"
VENDORPARAMETER="VENDOR=${PARAMETERSARRAY[1]}"
COMPILETARGETSARRAY=( `echo ${COMPILETARGETS}` )

if [ "${PARAMETERSARRAY[2]}" != "atp" ]
then
CUSTOMERPARAMETER="CUSTOMER=${PARAMETERSARRAY[2]}"
else
CUSTOMERPARAMETER=""
fi


if [ ${#COMPILETARGETSARRAY[@]} -lt ${MINICOMPILETARGETSNUM} ]
then
	echo "The compile targets ( ${COMPILETARGETS} ) are invalid."
	exit -2
fi

MAKETARGETS=`echo ${COMPILETARGETSARRAY[@]}`
CLEANTARGETS=`echo ${COMPILETARGETSARRAY[@]/%/-clean}`

echo "make ${VENDORPARAMETER} ${CUSTOMERPARAMETER} ${ATPICPCIPARAMETER} ${CLEANTARGETS}"
make ${VENDORPARAMETER} ${CUSTOMERPARAMETER} ${ATPICPCIPARAMETER} ${CLEANTARGETS}

if [ "${PARAMETERSARRAY[0]}" = "debug_yes" ]
then
	echo -ne "\ncompile debug flag...\n"
	make ${VENDORPARAMETER} ${CUSTOMERPARAMETER} ${ATPICPCIDEBUG}
fi

echo "make ${VENDORPARAMETER} ${CUSTOMERPARAMETER} ${ATPICPCIPARAMETER} ${MAKETARGETS}"
make ${VENDORPARAMETER} ${CUSTOMERPARAMETER} ${ATPICPCIPARAMETER} ${MAKETARGETS}

exit 0

