################### depend objects
OBJS = soap_common.o soap_ctrlpt.o soap_device.o


######################### compile options
CFLAGS = -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64

include $(TOPDIR)/package/atp/rule.mak


