################### depend objects
OBJS = attr.o document.o element.o ixml.o ixmlmembuf.o ixmlparser.o namedNodeMap.o node.o nodeList.o

######################### compile options
CFLAGS = -Wl,-allow-shlib-undefined

################### Yourself lib(if no, fill nothing)
EXTRA_LIB =

include $(TOPDIR)/package/atp/rule.mak
