################### depend objects
OBJS = httpparser.o httpreadwrite.o parsetools.o statcodes.o webserver.o
 
######################### compile options
CFLAGS = -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64

include $(TOPDIR)/package/atp/rule.mak


