################### depend objects
OBJS = http/httpparser.o http/httpreadwrite.o http/parsetools.o http/statcodes.o \
	   http/webserver.o uri/uri.o sock.o

######################### compile options
CFLAGS = -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64

include $(TOPDIR)/package/atp/rule.mak


