################### depend objects
OBJS = ssdp_ctrlpt.o ssdp_device.o ssdp_server.o

######################### compile options
CFLAGS = -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64

include $(TOPDIR)/package/atp/rule.mak


