#############################################################
#
# KIPV6
#
#############################################################

#
# Dependencies
#
KIPV6_DEPENDENCIES = 

#############################################################
### Version and change logs area
KIPV6_VERSION = V1.00

define KIPV6_CHANGELOGS
V1.00:
	1. First release by dongbin.

endef
#############################################################

KIPV6_TYPE=atpkconfig

define KIPV6_LINUX_CONFIGURE_CMDS
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IPV6,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_SUPPORT_ATP_IPV6_ENABLE,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IPV6_ROUTER_PREF,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IPV6_ROUTE_INFO,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IP6_NF_IPTABLES,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IP6_NF_FILTER,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IP6_NF_MANGLE,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IP6_NF_RAW,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IP6_NF_QUEUE,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_NETFILTER_XTABLES,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_NETFILTER_XT_TARGET_MARK,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_NETFILTER_XT_MATCH_MULTIPORT,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IPV6_MULTIPLE_TABLES,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IPV6_SUBTREES,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_NETFILTER_XT_MATCH_MAC,$$(KERNEL_CONFIG_FILE))
endef


$(eval $(call ATPTARGETS,package/atp/network/common/ipv6common/kernel,kipv6,BUILD_IPV6))