#############################################################
#
# KFIREWALL
#
#############################################################

#
# Dependencies
#
KFIREWALL_DEPENDENCIES = 

#############################################################
### Version and change logs area
KFIREWALL_VERSION = V1.00

define KFIREWALL_CHANGELOGS
V1.00:
	1. First release by Hou.

endef
#############################################################

KFIREWALL_TYPE=atpkconfig

define KFIREWALL_LINUX_CONFIGURE_CMDS
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_NETFILTER_XT_MATCH_DNS_FLT,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_NETFILTER_XT_MATCH_IPRANGE,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_NETFILTER_XT_MATCH_LIMIT,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_NETFILTER_XT_MATCH_MAC,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_NETFILTER_XT_MATCH_MULTIPORT,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_NETFILTER_XT_MATCH_STATE,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_NETFILTER_XT_MATCH_TIME,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IP_NF_MATCH_MISC,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IP_NF_TARGET_REJECT,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IP_NF_TARGET_LOG,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IP6_NF_MATCH_EUI64,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IP6_NF_MATCH_IPV6HEADER,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IP6_NF_MATCH_RT,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IP6_NF_TARGET_REJECT,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_IP6_NF_TARGET_LOG,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_BRIDGE_EBT_IP,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_BRIDGE_EBT_IP6,$$(KERNEL_CONFIG_FILE))
	$(call ATP_KCONFIG_ENABLE_OPT,CONFIG_BRIDGE_EBT_TIME,$$(KERNEL_CONFIG_FILE))
endef


$(eval $(call ATPTARGETS,package/atp/network/firewall/kernel,kfirewall,BUILD_FIREWALL_COMMON))
