################### depend objects
OBJS = membuffer.o strintmap.o upnp_timeout.o util.o

######################### compile options
CFLAGS = -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64

include $(TOPDIR)/package/atp/rule.mak


